version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=rubbituser"
      - "RABBITMQ_DEFAULT_PASS=Gdkl6CWaXjdY38GJU43KERFyMtSKqSWWzFVr8Ia9"
      - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"


    ports:
      - "5672:5672"
      - "15672:15672"

